<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile.

?>

<script>
require([
    'jquery',
    'mage/adminhtml/grid',
    'prototype'
], function(jQuery){

<!--

    var checkBoxes = $H({"1":0});
    var warning = false;
    if (checkBoxes.size() > 0) {
        warning = true;
    }
    jQuery('#in_lists_grid').val(checkBoxes.toQueryString());

    function registerUserRole(grid, element, checked)
    {
        if (checked) {
            checkBoxes.set(element.value, 0);
        } else {
            checkBoxes.unset(element.value);
        }
        $('in_lists_grid').value = checkBoxes.toQueryString();
        grid.reloadParams = {'in_lists_grid[]':checkBoxes.keys()};
    }

    function roleUsersRowClick(grid, event)
    {
		var trElement = Event.findElement(event, 'tr');
        var isInput   = Event.element(event).tagName == 'INPUT';
        if (trElement) {
            var checkbox = Element.getElementsBySelector(trElement, 'input');
            if(checkbox[0]){
                var checked = isInput ? !checkbox[0].checked : checkbox[0].checked;
                if (checked) {
                    if ( confirm("<?php echo __('Warning!\r\nThis action will remove this user from already assigned role\r\nAre you sure?') ?>") ) {
                        checkbox[0].checked = false;
                        checkBoxes.unset(checkbox[0].value);
                        varienElementMethods.setHasChanges(checkbox[0]);
                    } else {
                        checkbox[0].checked = true;
                    }
                } else {
                    checkbox[0].checked = true;
                    checkBoxes.set(checkbox[0].value, true);
                }

                $('in_lists_grid').value = checkBoxes.toQueryString();
                grid.reloadParams = {'in_lists_grid[]':checkBoxes.keys()};
            }
        }
    }

    function roleUsersRowInit(grid, row)
    {
        var checkbox = $(row).getElementsByClassName('checkbox')[0];
        if (checkbox) {
            if (checkbox.checked) {
                checkBoxes.set(checkbox.value, checkbox.checked);
            } else {
                checkBoxes.unset(checkbox.value);
            }

            $('in_lists_grid').value = checkBoxes.toQueryString();
            grid.reloadParams = {'in_lists_grid[]':checkBoxes.keys()};
        }
    }

    function massSelectUsers(allCheckbox)
    {
        /* if (!allCheckbox.checked && checkBoxes.size() > 0) {
            if (!confirm("<?php echo __('Warning!\r\nThis action will remove those users from already assigned roles\r\nAre you sure?') ?>") ) {
                allCheckbox.checked = false;
                return false;
            }
        } */
        listsGridJsObject.rows.each(function(row)
        {
            $(row).getElementsByClassName('checkbox')[0].checked = allCheckbox.checked;
            roleUsersRowInit(listsGridJsObject, row);
        });
    }
    Event.observe(window, "load", function(){
        listsGridJsObject.rowClickCallback = roleUsersRowClick;
        listsGridJsObject.initRowCallback = roleUsersRowInit;
        listsGridJsObject.checkboxCheckCallback = registerUserRole;
        listsGridJsObject.checkCheckboxes = massSelectUsers;
        listsGridJsObject.rows.each(function(row){roleUsersRowInit(listsGridJsObject, row)});
        $('in_lists_grid_old').value = $('in_lists_grid').value;
    });

//-->

});
</script>
